# Docker Compose para aplicação Fintech Microfrontends

services:
  # Serviço da aplicação React
  fintech-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: fintech-microfrontends
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - fintech-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Serviço para desenvolvimento (opcional)
  fintech-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: fintech-microfrontends-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - fintech-network
    profiles:
      - dev

networks:
  fintech-network:
    driver: bridge

volumes:
  node_modules: